### ISSUE TITLE
Request for documentation on how to format the output

### ISSUE THREAD

**Issue by bsaunder2002** [trac-hacks/WikiReportMacro#4]
I wrote a Trac report to query the database via SQL and fetch the last comment on a particular ticket ID.
[[WikiReport(10, TICKET=203)]]

This works but returns in the wiki page:
  Fri6-22-18 * Clean kitchen/ dishes * Finish cleaning / stage computer room * Clean master bathroom * Hang garage wall tarp * Clean garage so Gayle can park inside 

I'd like it to be processed by the wiki as wiki formatted text.

Do you know how to get WikiReportMacro to interpret the results as wiki text?
Using Trac 1.0.2.

For reference, SQL query in report is: 
select newvalue from ticket_change where
ticket=$TICKET
order by time desc
limit 1

**Comment by rdnvndr** [comment]
Try:
```
select newvalue as description from ticket_change where
ticket=$TICKET
order by time desc
limit 1
```
> description — Ticket description field, parsed through the wiki engine.

See:   https://trac.edgewall.org/wiki/TracReports
